LISTEN_LIST = ['填写你的微信用户名，不要备注']
DEEPSEEK_API_KEY = '填写你的DeepSeek API Key'
DEEPSEEK_BASE_URL = 'https://api.siliconflow.cn/v1/'
MODEL = 'deepseek-ai/DeepSeek-V3'
MAX_TOKEN = 2000
TEMPERATURE = 1.3
IMAGE_MODEL = 'stabilityai/stable-diffusion-3-medium'
IMAGE_SIZE = '960x1280'
BATCH_SIZE = '1'
GUIDANCE_SCALE = '3'
NUM_INFERENCE_STEPS = '4'
PROMPT_ENHANCEMENT = 'True'
TEMP_IMAGE_DIR = 'temp_images'
